import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './providers/Providers'
import { Header } from '@/components/organisms/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="cyber-void" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <a
          href="#forward-main"
          className="sr-only focus:not-sr-only focus:underline absolute top-2 left-2 z-50"
        >
          Skip Header
        </a>
        <Providers>
          <Header />
          <a
            id="forward-main"
            href="#main"
            className="sr-only focus:not-sr-only focus:underline px-2"
          >
            Skip to main content
          </a>
          <div id="page-wrapper" className="w-full min-h-screen p-4 font-mono py-4 mt-8">
            {/* Skip navigation link */}
            {children}
          </div>
          <footer className="text-xs text-muted py-6 text-center">
            © 2025 A2Z Blocks — Humbly built.
          </footer>
        </Providers>
      </body>
    </html>
  )
}
